#!/bin/sh

if [ "$#" != 0 ]; then
	echo "  gpull -- pull changes from origin"
	echo "  usage: gpull" 
	exit 1
fi

if !(git pull origin master); then
    echo "'git pull' failed."
    exit 1
fi

echo "Done."
