#!/bin/sh

if [ "$1" == "--help" ]; then
	echo "gpush -- push repo changes to origin"
	echo "usage: gpush" 
	exit 1
fi

if !(git add .); then
    echo "'git add' failed."
    exit 1
fi

if !(git commit); then
    echo "'git commit' failed."
    exit 1
fi

if !(git push origin master); then
	echo "'git push' failed" 
	exit 1
fi
