#!/bin/sh
if [ "$#" == 0 ]; then
	echo "gspush -- push subtree changes to subtree origin."
	echo "usage: gspush subname" 
	echo "e.g. gspush stupidgit"
	exit
fi
SUBNAME=$1
git subtree push --prefix=$SUBNAME --squash $SUBNAME master
